### ISSUE TITLE
Does not work when using title() method

### ISSUE THREAD

**Issue by noahlocke** [orlyapps/nova-belongsto-depend#11] opened 2018-09-29 02:33 UTC
The multi-select field is expecting a titleKey attribute for the custom label, but if the Nova Resource title is set with the title() method, then all you get is the Id in custom label.

**Comment by orlyapps** [comment] 2018-10-02 06:56
Thanks for this issus. Im looking into this.

**Comment by srottem** [comment] 2018-10-02 11:39
This is a simple fix; the default implementation of the title() method on the resource returns the value of the $title member variable, but if overridden it will return whatever the new function implementation is.  Just update the constructor for the NovaBelongsTo class to use this instead: `$this->titleKey = $resource::title();`

E.g.

```
    public function __construct($name, $attribute = null, $resource = null)
    {
        $resource = $resource ?? ResourceRelationshipGuesser::guessResource($name);
        parent::__construct($name, $attribute, $resource);

        $this->modelClass = get_class($resource::newModel());
        $this->modelPrimaryKey = $resource::newModel()->getKeyName();
        $this->titleKey = $resource::title();
        $this->optionResolveCallback = function () {
            return [];
        };
    });

```

**Comment by srottem** [comment] 2018-10-02 11:47
I'm also affected - I thought I had a fix for this but was wrong. :(

**Comment by orlyapps** [comment] 2018-10-04 07:54
Hello,

this is in my opinion not a bug. You can archive a custom title this way:

```php
class ExampleModel extends Model
{
    protected $appends = ['title'];


    public function getTitleAttribute()
    {
        return $this->attributes['name'] . ' custom';
    }
}


class ExampleModel extends Resource
{

    public static $model = 'App\ExampleModel';

    public static $title = 'title';

}

I have updated the demo project

https://github.com/orlyapps/laravel-nova-demo

**Closed** 2018-10-08 07:43 UTC
